### ISSUE TITLE
Null column values filled with previous column value

### ISSUE THREAD

**Issue by epuru4680** [mbleron/ExcelTable#42] opened 2023-01-18 17:49 UTC
hi mbleron, we are trying to load a excel file into oracle database table using ExcelTable.getRows and ExcelTable.getFile. It was working fine until our client changed format cells from text to general and custom mm/dd/yy to date *3/14/2012. with the new change it is filling the null column values with previous column value. Could you please check?

**Comment by mbleron** [comment] 2023-01-19 08:18
Hi, 

I've edited the issue so that it gets a proper title and description.

It looks like an old bug I fixed a while ago.
Could you please add a sample file to reproduce the issue? And the query you're using as well.
Thanks.

**Comment by epuru4680** [comment] 2023-01-19 15:46
Hi Mbleron,

Thanks for your quick response.  here is the code i am trying to test to replicate the issue.  please see in attached excel that Danfe, MISSINGCARRIERDATES, CURDATEBEYONDRODATE are nulls but this code brings previous not null column values.

please modify the location from 'OLM_NAS_PATH' to location where you are saving this file.

code used:
-----------
SELECT rownum,HQ_ID,SOLD_TO,RO_PROJECTED_DELIVERY_DATE,DAYS_BEYOND_APPLE_SCHED_DATE,CLASS,APPLE_PART_NUMBER,DELIVERYNUMBER,DELIVERYLINEITEMNUMBER,SALESORDERID,CUSTOMERPONUMBER,TRACKINGNUMBER,ORDERLINEQUANTITY,SHIPPEDQUANTITY,DANFE,CURRENTEVENTNAME,SHIPCONFIRMATION,SHIPPEDFISCALWEEK,SHIPMENTPICKEDUP,APPLESCHEDDELDATE,FIRSTCARRIERESTDATE,LASTCARRIERESTDATE,DELIVERYAPPOINTMENT,OUTFORDELIVERYDATE,DELIVEREDDATETIME,DELIVEREDFISCALWEEK,MISSINGCARRIERDATES,CURDATEBEYONDRODATE,UPC,APPLEPARTDESCR,APPPARENTPARTDESCR,CLASSDESCRIPTION,COLOR,APPSOLDTOCUSTID,APPSOLDTOCUSTNAME,CONSIGNEENUMBER,CONSIGNEENAME,ADDRESS,CITY,STATE,POSTALCODE,COUNTRY,ROPROJDELDATEDOW,RECEIVERSNAME,CARRIER,CAPACITYS,SHIPMENTORIGIN,APPLEID,APPLEIDNAME,CONFIGID,'IN_TRANSIT_QTD_AMR_pe_261802_20230118_2357.xlsx'
from table(
             ExcelTable.getRows(
              p_file  => ExcelTable.getFile('OLM_NAS_PATH','IN_TRANSIT_QTD_AMR_pe_261802_20230118_2357.xlsx')
            , p_sheet => 'Shipment_Data'
            , p_cols  => '"HQ_ID" VARCHAR2(150 CHAR),"SOLD_TO" VARCHAR2(150 CHAR),"RO_PROJECTED_DELIVERY_DATE" VARCHAR2(150 CHAR),"DAYS_BEYOND_APPLE_SCHED_DATE" VARCHAR2(150 CHAR),"CLASS" VARCHAR2(150 CHAR),"APPLE_PART_NUMBER" VARCHAR2(150 CHAR),"DELIVERYNUMBER" VARCHAR2(150 CHAR),"DELIVERYLINEITEMNUMBER" VARCHAR2(150 CHAR),"SALESORDERID" VARCHAR2(150 CHAR),"CUSTOMERPONUMBER" VARCHAR2(150 CHAR),"TRACKINGNUMBER" VARCHAR2(4000 CHAR),"ORDERLINEQUANTITY" NUMBER(10),"SHIPPEDQUANTITY" NUMBER(10),"DANFE" VARCHAR2(150 CHAR),"CURRENTEVENTNAME" VARCHAR2(150 CHAR),"SHIPCONFIRMATION" VARCHAR2(150 CHAR),"SHIPPEDFISCALWEEK" VARCHAR2(150 CHAR),"SHIPMENTPICKEDUP" VARCHAR2(150 CHAR),"APPLESCHEDDELDATE" VARCHAR2(150 CHAR),"FIRSTCARRIERESTDATE" VARCHAR2(150 CHAR),"LASTCARRIERESTDATE" VARCHAR2(150 CHAR),"DELIVERYAPPOINTMENT" VARCHAR2(150 CHAR),"OUTFORDELIVERYDATE" VARCHAR2(150 CHAR),"DELIVEREDDATETIME" VARCHAR2(150 CHAR),"DELIVEREDFISCALWEEK" VARCHAR2(150 CHAR),"MISSINGCARRIERDATES" VARCHAR2(150 CHAR),"CURDATEBEYONDRODATE" VARCHAR2(150 CHAR),"UPC" VARCHAR2(150 CHAR),"APPLEPARTDESCR" VARCHAR2(4000 CHAR),"APPPARENTPARTDESCR" VARCHAR2(4000 CHAR),"CLASSDESCRIPTION" VARCHAR2(4000 CHAR),"COLOR" VARCHAR2(150 CHAR),"APPSOLDTOCUSTID" VARCHAR2(150 CHAR),"APPSOLDTOCUSTNAME" VARCHAR2(150 CHAR),"CONSIGNEENUMBER" NUMBER(10),"CONSIGNEENAME" VARCHAR2(150 CHAR),"ADDRESS" VARCHAR2(500 CHAR),"CITY" VARCHAR2(150 CHAR),"STATE" VARCHAR2(150 CHAR),"POSTALCODE" VARCHAR2(150 CHAR),"COUNTRY" VARCHAR2(150 CHAR),"ROPROJDELDATEDOW" VARCHAR2(150 CHAR),"RECEIVERSNAME" VARCHAR2(150 CHAR),"CARRIER" VARCHAR2(150 CHAR),"CAPACITYS" VARCHAR2(4000 CHAR),"SHIPMENTORIGIN" VARCHAR2(150 CHAR),"APPLEID" VARCHAR2(150 CHAR),"APPLEIDNAME" VARCHAR2(150),"CONFIGID" VARCHAR2(150 CHAR)'
            , p_range => 'A7'
            ))

file used:
----------
[IN_TRANSIT_QTD_AMR_pe_261802_20230118_2357.xlsx](https://github.com/mbleron/ExcelTable/files/10458249/IN_TRANSIT_QTD_AMR_pe_261802_20230118_2357.xlsx)

**Comment by epuru4680** [comment] 2023-01-19 15:50
Hi Marc, Thanks for your quick response. I attached requested file and code to the issue I opened. Regards,PremaSent from my iPhoneOn Jan 19, 2023, at 3:18 AM, Marc Bleron ***@***.***> wrote:﻿
Hi,
I've edited the issue so that it gets a proper title and description.
It looks like an old bug I've fixed a while ago.
Could you please add a sample file to reproduce the issue?
Thanks.

**Comment by mbleron** [comment] 2023-01-19 20:20
I don't reproduce on the latest version. Which one are you using?

I suspect this is bug #26 which has been fixed in v5.1.1.

**Comment by epuru4680** [comment] 2023-01-20 01:53
this is the change history i see unable to tell what version it is though.

=========================================================================================
    Change history :
    Marc Bleron       2016-05-01     Creation
    Marc Bleron       2016-06-25     Added string_cache.delete on tableClose
                                     Added lob freeing
    Marc Bleron       2016-09-11     Added ECDS_MAX_OFFSET in function Zip_openArchive
    Marc Bleron       2016-10-30     New streaming read method for large files (requires
                                     Java)
                                     Added setFetchSize() procedure
    Marc Bleron       2017-05-14     Fixed ORA-06531 when file has no sharedStrings
    Marc Bleron       2017-05-28     Added support for password-encrypted workbooks
    Marc Bleron       2017-06-11     Added getCursor() function
    Marc Bleron       2017-07-10     Fixed bug when accessing zip archive created with
                                     data descriptors. (Un)compressed sizes and CRC-32
                                     are now read from central directory entries
    Marc Bleron       2017-07-14     Support for long identifiers
    Marc Bleron       2017-12-31     Added cell comments extraction
    Marc Bleron       2018-02-04     Added support for .xls files
    Marc Bleron       2018-03-17     Added support for large shared strings in versions
                                     prior 11.2.0.2
    Marc Bleron       2018-04-21     Added support for .xlsb files
    Marc Bleron       2018-04-24     Unzip utility : detection of stored files (no comp)
    Marc Bleron       2018-05-12     Added support for ODF spreadsheets (.ods)
    Marc Bleron       2018-08-22     new API for DML operations
    Marc Bleron       2018-11-02     Added multi-sheet support
    Marc Bleron       2019-03-31     Added default value feature to DML API
    Marc Bleron       2019-04-02     Added support for XML spreasheetML files
    Marc Bleron       2019-05-12     Fix : requested rows count wrongly decremented for
                                           empty row
                                     Fix : getCursor() failure with multi-sheet support
    Marc Bleron       2019-05-21     Added flat file support
    Marc Bleron       2019-08-25     Fix : Exception when loading a zero or negative
                                           value as a NUMBER(p) or NUMBER(p,s)
                                     Fix : DML API : Default value not applied for
                                           empty cells
    Marc Bleron       2019-09-26     Fix : Error when using FOR ORDINALITY with a
                                           positional text data source
    Marc Bleron       2019-10-02     Added strict OOXML support
    Marc Bleron       2019-11-03     Added streaming read method for ODF spreadsheets
    Marc Bleron       2020-02-29     Added cellNote attribute to ExcelTableCell
====================================================================================== */


I see one more change after the last one I have in GITHUB.  let me take the latest change and retest it Marc. 

this change is missing in mine will take latest code test it and update you Marc
 Marc Bleron       2021-02-12     Fix : wrong value for cells containing an empty 
                                           shared string

Thank you!!
Regards,
Prema

**Comment by epuru4680** [comment] 2023-01-20 02:45
Hi Marc,

After recompiling latest code this issue is not reproduced.  Thanks a lot Marc for your quick reponse.

Regards,
Prema

**Comment by mbleron** [comment] 2023-01-20 09:24
You're welcome.

**Closed as completed by mbleron** 2023-01-20 09:24 UTC
Labels: duplicate

**Comment by epuru4680** [comment] 2023-01-20 14:30
Awesome, thanks!
