### ISSUE TITLE
PLS-00302: component 'EXCELTABLEIMPL' must be declared

### ISSUE THREAD

**Issue by acoder8432** [mbleron/ExcelTable#9] opened 2019-02-08 18:25 UTC
Not sure if this is a bug/issue or an install issue.  
But I couldn't find a user forum to post to, or the authors email.
If there is a better location to post this please let me know and I will post there.

Installing the following :
ExcelTable 2.3.2 (last commit October 28, 2018)
CDFReader        (last commit April 1, 2018)
OfficeCrypto     (last commit August 24, 2018)

My oracle version - Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

Granted execute on sys.dbms_crypto to user qms_user
All objects built using userid qms_user per order in readme with no errors.

@xutl_cdf.pks
@xutl_cdf.pkb
@xutl_offcrypto.pks
@xutl_offcrypto.pkb
@ExcelTableCell.tps
@ExcelTableCellList.tps
@xutl_xls.pks
@xutl_xls.pkb
@xutl_xlsb.pks
@xutl_xlsb.pkb
@ExcelTableImpl.tps
@ExcelTable.pks
@ExcelTable.pkb
@ExcelTableImpl.tpb

I did not perform the java install because I was only interested in the ExcelTable.getRows functionality to replace the following :

CREATE TABLE NewTable as (SELECT * FROM External_file_as_table);    
The current external file is a tab delimited text file which is being replace with a xlsx file. 
(hence the need for ExcelTable)

Using the Examples section of the readme file I moved the sample spreadsheet sample_3.xlsx to a directory named DAT_DIR and then ran the following sample code from the readme as qms_user:
(changing the readme directory of XL_DATA_DIR to my directory of DAT_DIR)

select t.* 
from table(
       ExcelTable.getRows(
         ExcelTable.getFile('DAT_DIR','sample_3.xlsx')
       , 'DataSource'
       , ' "SRNO"    number
         , "NAME"    varchar2(10)
         , "VAL"     number
         , "DT"      date
         , "SPARE1"  varchar2(6)
         , "SPARE2"  varchar2(6)'
       , 'A2'
       )
     ) t
;

And received the following error :

ORA-06550: line 4, column 24:
PLS-00302: component 'EXCELTABLEIMPL' must be declared
ORA-06550: line 4, column 6:
PL/SQL: Statement ignored
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error.
*Action:

I shorted the test script trying to validate the install.  I ran the following :

select ExcelTable.getFile('DAT_DIR','sample_3.xlsx') from dual;

The result was (BLOB) as expected.  So I feel that at least a portion of the install was successful.

My first instinct was that the getRows function was not defined in the ExcelTable.pkb package body source.
But then I realized that the getRows function in the ExcelTable.pks package header source implements ExcelTableImpl.

I'm assuming this is an install issue on my part but I couldn't find a user forum to check for help.
Help from anyone would be greatly appreciated.

Thanks,
Roy

**Comment by mbleron** [comment] 2019-02-10 17:12
Hi Roy,

You're posting at the correct place.
Looks like an install issue indeed.

- Are all objects compiled with no error? Check USER_ERRORS dictionary view, or any modern IDE to confirm that in a glance.

- Are you running the SQL statement as the same user as the owner of the objects?

**Comment by acoder8432** [comment] 2019-02-11 18:25
I was using SQL Developer when compiling everything.  No errors were thrown during compile and USER_ERRORS and ALL_ERRORS are empty.

I created all objects with a user of QMS_USER, and I ran the test scripts as QMS_USER.

**Comment by mbleron** [comment] 2019-02-14 11:47
I've been doing a fresh install on 11.2.0.4, using a newly created user with the minimum required privileges.
Everything went OK, see output below from SQL*Plus : 

```
C:\Users\Marc>cd c:\dev\oracle

c:\dev\oracle>sqlplus sys@ora11g as sysdba

SQL*Plus: Release 11.2.0.4.0 Production on Thu Feb 14 12:00:20 2019

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Enter password:

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> create user qms_user identified by qms_user default tablespace users;

User created.

SQL> grant create session to qms_user;

Grant succeeded.

SQL> grant create procedure to qms_user;

Grant succeeded.

SQL> grant create type to qms_user;

Grant succeeded.

SQL> grant read on directory xl_data_dir to qms_user;

Grant succeeded.

SQL> grant execute on sys.dbms_crypto to qms_user;

Grant succeeded.

SQL>
SQL> conn qms_user/qms_user@ora11g
Connected.
SQL>
SQL> @MSUtilities\CDFReader\xutl_cdf.pks

Package created.

SQL> @MSUtilities\CDFReader\xutl_cdf.pkb

Package body created.

SQL> @MSUtilities\OfficeCrypto\xutl_offcrypto.pks

Package created.

SQL> @MSUtilities\OfficeCrypto\xutl_offcrypto.pkb

Package body created.

SQL> @ExcelTable\ExcelTableCell.tps

Type created.

SQL> @ExcelTable\ExcelTableCellList.tps

Type created.

SQL> @ExcelTable\xutl_xls.pks

Package created.

SQL> @ExcelTable\xutl_xls.pkb

Package body created.

SQL> @ExcelTable\xutl_xlsb.pks

Package created.

SQL> @ExcelTable\xutl_xlsb.pkb

Package body created.

SQL> @ExcelTable\ExcelTableImpl.tps

Type created.

SQL> @ExcelTable\ExcelTable.pks

Package created.

SQL> @ExcelTable\ExcelTable.pkb

Package body created.

SQL> @ExcelTable\ExcelTableImpl.tpb

Type body created.

SQL>
SQL>
SQL> set lines 200
SQL> set pages 1000
SQL>
SQL> select t.*
  2  from table(
  3         ExcelTable.getRows(
  4           ExcelTable.getFile('XL_DATA_DIR','sample_3.xlsx')
  5         , 'DataSource'
  6         , ' "SRNO" number
  7           , "NAME" varchar2(10)
  8           , "VAL" number
  9           , "DT" date
 10           , "SPARE1" varchar2(6)
 11           , "SPARE2" varchar2(6)'
 12         , 'A2'
 13         )
 14       ) t
 15  ;

      SRNO NAME              VAL DT        SPARE1 SPARE2
---------- ---------- ---------- --------- ------ ------
         1 LINE-00001 12236.3667 08-OCT-15
         2 LINE-00002 72259.9805 30-MAY-12
         3 LINE-00003 19670.5563 22-DEC-18        OK
         4 LINE-00004 58050.7687 20-JUN-03        OK
         5 LINE-00005  69408.796 24-JUN-11
         6 LINE-00006 71611.4463 06-AUG-14        OK
         7 LINE-00007 88220.2497 22-JAN-09
         8 LINE-00008 6399.55197 09-MAY-18
         9 LINE-00009  20486.593 21-NOV-03
        10 LINE-00010  80027.221 27-FEB-25
        11 LINE-00011 79219.8838 17-FEB-20
        12 LINE-00012 91934.5566 25-JUN-16
        13 LINE-00013 41883.6291 13-JUN-21
        14 LINE-00014 50252.9451 05-DEC-21
        15 LINE-00015 12131.0201 27-AUG-01
        16 LINE-00016 53239.5674 24-DEC-15
        17 LINE-00017 9269.61807 25-JAN-08
        18 LINE-00018 52515.9927 04-NOV-21
        19 LINE-00019 92361.1468 11-JAN-22
        20 LINE-00020 66578.9649 17-AUG-04
        21 LINE-00021 96165.5873 09-APR-19        OK
        22 LINE-00022 91010.0893 25-FEB-27
        23 LINE-00023 89252.5602 19-JAN-21
        24 LINE-00024 96876.0131 22-FEB-20
        25 LINE-00025 1625.12744 07-MAY-21
        26 LINE-00026 32577.6701 19-MAR-08        OK
        27 LINE-00027 19802.9345 20-AUG-17
        28 LINE-00028 31026.3986 18-OCT-03
        29 LINE-00029 47938.6004 30-OCT-03        OK
        30 LINE-00030 73906.3478 09-JUL-22
        31 LINE-00031 77582.3971 07-JUL-16
        32 LINE-00032 90805.0208 19-APR-03
        33 LINE-00033 5409.49683 15-FEB-20
        34 LINE-00034 9653.35709 09-MAY-12
        35 LINE-00035 21055.2283 08-NOV-15
        36 LINE-00036 20882.3785 28-MAY-16
        37 LINE-00037 31176.8991 04-JUL-01
        38 LINE-00038 73264.0235 24-AUG-07
        39 LINE-00039 13607.1512 10-JUL-23
        40 LINE-00040 34871.1547 27-JUN-06
        41 LINE-00041 41611.4152 04-JUN-13
        42 LINE-00042 54150.6427 10-SEP-01
        43 LINE-00043  39650.126 12-APR-10
        44 LINE-00044 31630.0748 26-FEB-13
        45 LINE-00045 83493.1366 08-OCT-09
        46 LINE-00046 64519.4063 09-FEB-11
        47 LINE-00047 73011.7631 04-SEP-25
        48 LINE-00048 43576.8252 15-SEP-09
        49 LINE-00049 52723.3727 15-DEC-13
        50 LINE-00050 65231.2593 14-FEB-17
        51 LINE-00051 38130.8722 13-JAN-21
        52 LINE-00052 95895.6759 07-JUL-06
        53 LINE-00053 48426.7684 04-NOV-23
        54 LINE-00054 41869.2266 16-JUL-26
        55 LINE-00055 88862.2303 20-OCT-21
        56 LINE-00056 15847.6545 27-MAY-03
        57 LINE-00057 40063.1391 07-JUL-21
        58 LINE-00058 80298.2343 17-JUL-12
        59 LINE-00059 18426.7455 19-AUG-08
        60 LINE-00060 89552.3784 11-DEC-09
        61 LINE-00061  20159.329 14-JUL-23
        62 LINE-00062 81758.8539 02-OCT-03
        63 LINE-00063 51747.3087 17-DEC-00
        64 LINE-00064 32556.1611 27-JAN-00
        65 LINE-00065 68294.1983 03-DEC-24
        66 LINE-00066 81990.9014 10-AUG-09
        67 LINE-00067 55437.1477 06-OCT-10
        68 LINE-00068  11132.247 15-JUN-16
        69 LINE-00069 31909.9922 30-SEP-24
        70 LINE-00070 8216.74673 29-JUL-25
        71 LINE-00071 6883.89881 06-OCT-26
        72 LINE-00072 34485.0989 05-NOV-20
        73 LINE-00073 13592.9864 15-DEC-00
        74 LINE-00074  32521.817 14-FEB-19
        75 LINE-00075 18619.1185 14-SEP-00
        76 LINE-00076 63116.9766 22-NOV-24
        77 LINE-00077 59098.2854 23-OCT-01
        78 LINE-00078 10118.4667 13-AUG-25
        79 LINE-00079 34582.8938 01-SEP-02
        80 LINE-00080 8309.31673 14-DEC-06
        81 LINE-00081 94249.0089 02-JUL-12
        82 LINE-00082  59713.986 26-NOV-24
        83 LINE-00083 8026.94758 27-MAR-09
        84 LINE-00084 8361.70242 25-MAY-24
        85 LINE-00085 68527.7834 31-OCT-21
        86 LINE-00086 1474.37904 27-JUL-04
        87 LINE-00087 36872.5231 04-APR-07
        88 LINE-00088 50031.0421 10-NOV-17
        89 LINE-00089 14406.9723 16-AUG-10
        90 LINE-00090 27242.1456 31-JAN-05
        91 LINE-00091 56381.6959 10-AUG-12
        92 LINE-00092  71732.164 23-JAN-03
        93 LINE-00093 25271.7241 16-FEB-12
        94 LINE-00094 61967.5798 20-JUL-09
        95 LINE-00095  85782.547 22-SEP-14
        96 LINE-00096 69633.5719 20-MAR-22
        97 LINE-00097 75448.2015 13-NOV-10
        98 LINE-00098  42884.264 28-JAN-24
        99 LINE-00099 22901.7672 29-FEB-24
       100 LINE-00100  34917.174 26-JUN-22

100 rows selected.

```

Could you try following the same steps, and see if you get anything different?

**Comment by mbleron** [comment] 2019-03-31 13:36
Closing this as non reproducible.

**Closed as completed by mbleron** 2019-03-31 13:36 UTC
